---
user: adam

home_path: /home/adam
downloads_path: /home/adam/Downloads

github_user: adamayd

dotfiles_repo: https://github.com/adamayd/dotfiles
dotfiles_repo_ssh: git@github.com:adamayd/dotfiles.git 
dotfiles_path: /home/adam/dotfiles
dotfiles_files:
  - bashrc
  - gitconfig
  - config/ranger/rc.conf

    #vscode_extenstions:
    #- eg2.tslint

base_utilities:
  - ranger
  - vifm
  - strace
  - curl
  - wget
  - tmux
  - xclip
  - jq
  - fzf
  - bat
  - dnf-plugins-core
  - make
  - automake
  - kernel-devel
  # TODO:- fuse-exfat
  # TODO:- exfat-utils

apps_cli:
  - cmatrix
  - neofetch
  - fortune-mod
  - cowsay

apps_gui:
  - google-chrome-stable
  - calibre
  - gnome-tweaks
  - evolution

apps_flatpak:
  - im.riot.Riot
  - com.slack.Slack
  - com.discordapp.Discord
  - cc.arduino.arduinoide
  - org.fritzing.Fritzing

nvm_env: 
  nvm_dir: /home/adam/.nvm
