---
- hosts: all

  vars_files:
    - config.yml

  become: yes

  tasks:
    - name: "Update the system"
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - import_tasks: tasks/base.yml
    #- import_tasks: tasks/security.yml
    #- import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/languages.yml
    - import_tasks: tasks/vim.yml
    #- import_tasks: tasks/software.yml
    #- import_tasks: tasks/flatpak.yml
    #- import_tasks: tasks/docker.yml
    #- import_tasks: tasks/vscode.yml
    #- import_tasks: tasks/terminal.yml
    #- import_tasks: tasks/cloudtools.yml
