---
- hosts: all

  vars_files:
    - config.yml

  become: yes

  tasks:
    - name: "Update the system"
      dnf:
        name: "*"
        state: latest
      
    - name: "Install base utilities"
      dnf:
        name: "{{ item }}"
        state: latest
      loop: "{{ base_utilities }}"
      

    - import_tasks: tasks/security.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/languages.yml
    - import_tasks: tasks/software.yml
    - import_tasks: tasks/flatpak.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/terminal.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/cloudtools.yml
