---
  - name: Add Flathub
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: Install Flatpak Apps
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    loop: "{{ apps_flatpak }}"

