---
  - name: Add VSCode repo
    ansible.builtin.yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode/
      enabled: yes
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Install VS Code
    ansible.builtin.dnf:
      name: code
      state: latest

  # code --install-extensions
