---
  - name: Link dotfiles
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/home/{{ item }}"
      dest: "{{ home_path }}/.{{ item }}"
      owner: adam
      group: adam
      follow: false
      force: yes
      state: link
    loop: "{{ dotfiles_files }}"

