---
  - name: Install CLI Apps
    dnf:
      name: "{{ item }}"
      state: latest 
    loop: "{{ apps_cli }}"
    
  - name: Install GUI Apps
    dnf:
      name: "{{ item }}"
      state: latest
    loop: "{{ apps_gui }}"

        ### Issue with Keybase GPG key not generating to new standard for RPM in F35
        ### https://github.com/keybase/client/issues/24637 - Started again in late Jan 2022
        #- name: Install Keybase RPM
        #yum:
        #name: https://prerelease.keybase.io/keybase_amd64.rpm
        #state: present
