---
user: aayd
github_user: adamayd

home_path: /Users/{{ user }}/
downloads_path: {{ home_path }}Downloads/

configure_dotfiles: true
dotfiles_repo: https://github.com/{{ github_user }}/dotfiles
dotfiles_repo_ssh: git@github.com:{{ github_user }}/dotfiles.git 
dotfiles_path: {{ home_path }}dotfiles/
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .config/ranger/rc.conf
  - .vimrc

base_utilities:
  - ranger
  - curl
  - wget
  - tmux
  - jq
  - fzf

nvm_env: 
  nvm_dir: {{ home_path }}.nvm

configure_osx: true

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Maps
  - Contacts
  - Reminders
  - Notes
  - Photos
  - FaceTime
  - Music
  - News
  - App Store
dockitems_persist:
  - name: "Chrome"
    path: "/Applications/Chrome.app"
    pos: 4

configure_sudoers: false
sudoers_customer_config: ''

