---
user: aayd

home_path: /Users/aayd/
downloads_path: /Users/aayd/Downloads

github_user: adamayd

dotfiles_repo: https://github.com/adamayd/dotfiles
dotfiles_repo_ssh: git@github.com:adamayd/dotfiles.git 
dotfiles_path: /home/adam/dotfiles
dotfiles_files:
  - bashrc
  - gitconfig
  - config/ranger/rc.conf

    #vscode_extenstions:
    #- eg2.tslint

base_utilities:
  - ranger
  - curl
  - wget
  - tmux
  - jq
  - fzf

apps_cli:
  - cmatrix
  - neofetch
  - fortune-mod
  - cowsay

nvm_env: 
  nvm_dir: /home/adam/.nvm
